name: ✨ 풀 리퀘스트 작성
description: 완성된 기능을 풀 리퀘스트 작성할 때 사용하세요
title: "✨ 브랜치이름 -> 병합할 브랜치 이름 (#이슈번호)"
labels: ["enhancement"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: 작업 내용
      placeholder: 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
  - type: textarea
    id: description
    attributes:
      label: 리뷰 요구사항 (선택 사항)
      placeholder: 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
